# WProxy configuration file

# Listening address
listen_address = '127.0.0.1:1080'

# User authentication information
[users]
# Format: username = 'password'
# Example: admin = 'password'

# Buffer size (1-65536)
buffer_size = 4096

# Log settings
[log]
# Level for the log (Off, Error, Warn, Info, Debug, Trace)
level = "Info"
# Path for the log file
path = "logs/rust-proxy.log"
# Pattern for the log file archive
archive_pattern = "logs/archive/rust-proxy-{}.log"
# Number of log files to keep
file_count = 5
# Size of each log file (in MB)
file_size = 10